name: Build and Artifact

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64
          - linux-arm64
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
        include:
          - target: linux-amd64
            goos: linux
            goarch: amd64
            ext: ""
          - target: linux-arm64
            goos: linux
            goarch: arm64
            ext: ""
          - target: darwin-amd64
            goos: darwin
            goarch: amd64
            ext: ""
          - target: darwin-arm64
            goos: darwin
            goarch: arm64
            ext: ""
          - target: windows-amd64
            goos: windows
            goarch: amd64
            ext: ".exe"
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          OUTPUT_DIR: dist/${{ matrix.target }}
          OUTPUT_NAME: bridge${{ matrix.ext }}
        run: |
          mkdir -p "${OUTPUT_DIR}"
          go build -ldflags="-s -w" -trimpath -o "${OUTPUT_DIR}/${OUTPUT_NAME}" ./
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-${{ matrix.target }}
          path: dist/${{ matrix.target }}/bridge${{ matrix.ext }}
          if-no-files-found: error
