name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5
